### ISSUE TITLE
Find a place for the page to live

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/planetfour-terrains-guide#9]
This page needs to be uploaded to an S3 bucket, something like `planetfour-guide.zooniverse.org`.

@camallen, this should be fairly trivial to set up, right?

**Comment by camallen** [comment]
@simoneduca we have a preview bucket for this `preview.zooniverse.org/planetfour_guide` work work.

Out of interest, what's this project?

**Comment by simoneduca** [comment]
@camallen It's a stand alone static page. Something that Chris agreed to.

**Comment by camallen** [comment]
OK - so we can create that landing page and get that domain pointing it. However, we've actually got fields for the spotters guide in the API, [here](https://github.com/zooniverse/Panoptes/blob/b775ba6d712c0a4d186a1b17fcf91e7e42d9e9af/db/schema.rb#L152). That field doesn't currently support markdown but we can update it so that it can. Then it's just up to the front end to display this page as per the other pages.

I think we should modify these api fields and then link them up the project builder / front end. That way it's up to project teams to create this content.

This is a similar issue with the team page https://github.com/zooniverse/Panoptes-Front-End/issues/568

**Comment by simoneduca** [comment]
@camallen I think that's certainly the way to go for anything that will come up. For this though, because it's something that needs to go out of the door asap, I'd suggest we just put it in a bucket.
Could you grant me Zooniverse credentials for AWS? Alternatively, do you have time to do it today and I can watch?

**Comment by camallen** [comment]
@simoneduca yep, let's get this setup today.

**Comment by simoneduca** [comment]
@camallen sweet!

**Comment by rogerhutchings** [comment]
If you merge #10, you can add the deploy target to `package.json`

**Comment by rogerhutchings** [comment]
Fixed via 11cdeba2e008de3400eb3499980e34708b5a981e
